server:
  port: 19095 # Auth 서비스 포트 번호

spring:
  application:
    name: auth-service # 애플리케이션 이름

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db # postgreSql URL
    username: postgres # 데이터베이스 사용자명
    password: ${DB_PASSWORD} # 데이터베이스 비밀번호
    driver-class-name: org.postgresql.Driver # postgreSql 드라이버
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # PostgreSQL에 맞는 Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

#  data:
#    redis:
#      host: localhost
#      port: 6379
#      username: default
#      password: systempass

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/ # Eureka URL

service:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    # JWT 비밀키

    access-expiration: 3600000 # JWT 만료 시간 (ms)

feign:
  client:
    config:
      default:
        retryer: true # 재시도 활성화
        requestOptions:
          connectTimeout: 1000 # 연결 제한 시간
          readTimeout: 2000    # 읽기 제한 시간