server:
  port: 19097

spring:
  application:
    name: logistic-service

  config:
    import:
      - optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PW}
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      minimum-idle: 5
      maximum-pool-size: 20
      transaction-isolation: TRANSACTION_READ_COMMITTED

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 500
    open-in-view: false

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6380
      username: default
      password: ${REDIS_PW}

logging:
  level:
    root: INFO
    com.your.package.FeignConfig: WARN
    org.hibernate: WARN
    org.springframework.cache: DEBUG
    org.springframework.data.redis: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/ # Eureka URL

naver:
  coordinate-url: https://naveropenapi.apigw.ntruss.com/map-geocode/v2/geocode
  drive-url: https://naveropenapi.apigw.ntruss.com/map-direction/v1/driving
  rest-api-key-id: ${X-NCP-APIGW-API-KEY-ID}
  rest-api-key: ${X-NCP-APIGW-API-KEY}

feign:
  client:
    config:
      default:
        retryer: true # 재시도 활성화
        requestOptions:
          connectTimeout: 1000 # 연결 제한 시간
          readTimeout: 2000    # 읽기 제한 시간
